POST /v1/payments HTTP/1.1
Content-Type: application/json
Authorization: Bearer T8axbJqaQZYSUZbBL25FOtu1pxz3fmmetoxO8CV4t88M
Content-Length: 730

{
  "intent":"sale",
  "payer":{
    "payment_method":"credit_card",
    "funding_instruments":[
      {
        "credit_card":{
          "number":"4417119669820331",
          "type":"visa",
          "expire_month":10,
          "expire_year":2017,
          "cvv2":"748",
          "first_name":"Amy",
          "last_name":"Cass",
          "billing_address":{
            "postal_code":"59070",
            "country_code":"US"
          }
        }
      }
    ]
  },
  "transactions":[
    {
      "amount":{
        "total":"18.67",
        "currency":"USD",
        "details":{
          "subtotal":"17.41",
          "tax":"0.23",
          "shipping":"1.03"
        }
      },
      "description":"web sale"
    }
  ]
}